[window]
padding =  { x = 10, y = 10 }
decorations = "None"
opacity = 0.7

[font]
normal = { family = "JetBrainsMono NF Medium", style = "Medium"}
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam" }
thickness = 0.2

[colors.primary]
foreground = "#E2946D"
background = "#090c12"
dim_foreground = "#1b1011"

[colors.normal]
black = "#090c12"
red = "#ff0000"
green = "#B54B25"
yellow = "#B54B25"
blue = "#3B5D6B"
magenta = "#B54B25"
cyan = "#E2946D"
white = "#ffffff"

[colors.bright]
black = "#090c12"
red = "#ff0000"
green = "#B54B25"
yellow = "#B54B25"
blue = "#3B5D6B"
magenta = "#B54B25"
cyan = "#E2946D"
white = "#ffffff"

[colors.dim]
black = "#090c12"
red = "#ff0000"
green = "#B54B25"
yellow = "#B54B25"
blue = "#3B5D6B"
magenta = "#B54B25"
cyan = "#E2946D"
white = "#ffffff"

